## Use https://github.com/sj26/rspec_junit_formatter to generate a JUnit report format XML file with rspec
java:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
