image: maven:latest

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - deploy

build-maven:
  stage: build
  script:
    - echo "Compiling the code ..."
    - mvn build
    - echo "Compile complete."

test-maven:
  stage: test
  script:
    - echo "Running unit tests ..."
    - mvn test
    - echo "Tests finished."
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
