image: maven:latest

stages:
  - build
  - test

build-maven:
  stage: build
  script:
    mvn build

test-maven:
  stage: test
  script:
    mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
